# Generated by Django 4.0.1 on 2022-01-04 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
                ('deadline', models.IntegerField(default=0)),
                ('created', models.DateTimeField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('homework', models.CharField(max_length=30)),
                ('solution', models.CharField(max_length=30)),
                ('created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('teacher_ptr', models.OneToOneField(auto_created=True,
                                                     on_delete=django.
                                                     db.models.
                                                     deletion.CASCADE,
                                                     parent_link=True,
                                                     primary_key=True,
                                                     serialize=False,
                                                     to='polls.teacher')),
            ],
            bases=('polls.teacher',),
        ),
    ]
